[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers"

[env]
NODE_ENV = "production"
PYTHONPATH = "/app"
PORT = "8000"
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"
