[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --no-access-log"

[env]
# Application
NODE_ENV = "production"
PYTHONPATH = "/app"
PORT = "8000"
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"

# Database
DATABASE_URL = "${MONGO_URL}"

# CORS (update with your frontend URL)
ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:8000"

# Security
SECRET_KEY = "your-secure-secret-key-change-this"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "1440"

# LLM Configuration (set these in Railway dashboard)
# GOOGLE_API_KEY = ""
# OPENAI_API_KEY = ""
# ANTHROPIC_API_KEY = ""
DEFAULT_LLM_PROVIDER = "google"
DEFAULT_LLM_MODEL = "gemini-1.5-flash"
MAX_TOKENS_DEFAULT = "1000"
TEMPERATURE_DEFAULT = "0.7"
