[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile.railway"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

# Configure the number of workers based on available CPU cores
[deploy.worker]
maxConcurrentRequests = 100
memoryLimit = 1024
cpuLimit = 1.0

[env]
# Application
NODE_ENV = "production"
PYTHONPATH = "/app"
PORT = "8000"
PYTHONUNBUFFERED = "1"
ENVIRONMENT = "production"

# Database
DATABASE_URL = "${MONGO_URL}"

# CORS (update with your frontend URL)
ALLOWED_ORIGINS = "*"

# Security
SECRET_KEY = "your-secure-secret-key-change-this"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = "1440"

# LLM Configuration (set these in Railway dashboard)
# GOOGLE_API_KEY = ""
# OPENAI_API_KEY = ""
# ANTHROPIC_API_KEY = ""
DEFAULT_LLM_PROVIDER = "google"
DEFAULT_LLM_MODEL = "gemini-1.5-flash"
MAX_TOKENS_DEFAULT = "1000"
TEMPERATURE_DEFAULT = "0.7"
