[build]
builder = "dockerfile"
dockerfilePath = "frontend/Dockerfile"
dockerContext = "frontend"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
REACT_APP_ENV = "production"
